---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Данные, вводимые пользователем при регистрации, должны проверяться на уникальность
  - Данные, вводимые пользователем при регистрации, должны позволять коммуникацию с ним при необходимости
  - Язык отображения страниц сайта при первоначальной загрузке должен выбираться на основе кодировки/языка браузера клиента либо на основе данных геолокации (с возможностью выбора языка вручную)
  - Для всех представленных к выбору пользователем языков отображения страниц сайта должна существовать привязка соответствующей языку валюты, которая отображается "по умолчанию" (Русский - рубль, Английский - доллар)
  - При изменении языка отображения сайта меняется валюта цен на товары с автоматическим пересчётом по заданному курсу 